### ISSUE TITLE
Provide the complete GML XML -> GeoJSON parsing example

### ISSUE THREAD

**Issue by highsource** [derhuerst/parse-gml-polygon#3]
At the moment there is no complete GML XML parsing example - neither in the tests nor in the documentation.

Assuming I have an XML string or an URL of the XML document, how do I parse it into GeoJSON?

**Comment by derhuerst** [comment]
There's [code showing how to use `xml-reader` deeply hidden inside `query-fis-broker-wfs`](https://github.com/derhuerst/query-fis-broker-wfs/blob/cc2b8b23f084b621141948b4b0e4a5216d31eec7/lib/request.js#L65-L90). I will amend the readme with an example showing how to parse an XML string and an XML file.
